# dataset
dataset: OpenDialKG
tokenize:
  rec: bert
# tokenize path
rec_tokenize_path: 'bert-base-uncased'
# dataloader
context_truncate: 256
response_truncate: 30
item_truncate: 100
scale: 0.01
# model
rec_model: BERT
# pretrained path
rec_pretrained_path: 'bert-base-uncased'
# optim
rec:
  epoch: 1
  batch_size: 8
  optimizer:
    name: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 0.0000
  lr_bert: !!float 1e-5
