# dataset
dataset: TGReDial
tokenize:
  policy: bert
# tokenize path
policy_tokenize_path: 'bert-base-chinese'
# dataloader
context_truncate: 256
response_truncate: 30
item_truncate: 100
scale: 1
# model
policy_model: ConvBERT
# pretrained path
policy_pretrained_path: 'bert-base-chinese'
# optim
policy:
  epoch: 50
  batch_size: 8
  weight_decay: 0.01
  optimizer:
    name: AdamW
    lr: !!float 1e-5
  early_stop: true
  stop_mode: max
  impatience: 3