# dataset
dataset: ReDial
tokenize:
  rec: bert
# tokenize path
rec_tokenize_path: 'data/model/pretrain/bert/en'
# dataloader
context_truncate: 256
response_truncate: 30
item_truncate: 100
scale: 0.01
# model
rec_model: Popularity
# optim
rec:
  epoch: 1
  batch_size: 1024
  optimizer:
    name: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 0.0000
  lr_bert: !!float 1e-5
